### ISSUE TITLE
m3 macbook air

### ISSUE THREAD

**Issue by Jackstuch1990** [term7/DaemonLeash#2]
hello trying to run this on a m3 MacBook air.

do you know if this will still work I cant get it to install.

sudo /Users/jackstuchbery/Documents/DaemonLeash-master/Install_DaemonLeash.sh
sudo: /Users/jackstuchbery/Documents/DaemonLeash-master/Install_DaemonLeash.sh: command not found

any idea's much appreciated

Jack

**Comment by Jackstuch1990** [comment]
i have fixed this in a terminal you need to open the directory then you need this command

sudo sh /Users/jackstuchbery/Documents/DaemonLeash-master/Install_DaemonLeash.sh

**Comment by term7** [comment]
Glad you figured it out! Yes that is how you execute a shell script.
